- src/PhpBrew/Downloader/UrlDownloader.php
- tests/PhpBrew/Downloader/UrlDownloaderTest.php
To resolve #443 .
Use `Utils::system` method to download a file when wget or curl is used in `UrlDownloader`.
Users who don't enable curl extension can download files correctly.
Add some test cases for `UrlDownloaderTest`.
> Fixes a bug that donwloading a file using wget or curl always fails even when it succeeds.

- src/PhpBrew/Downloader/UrlDownloader.php
To remove redundant if statements which should be removed in #444 . `Utils::system` method throws an exception if command fails, so there is no need to throw an exception after calling `Utils::system`.
> Removes redundant if statements in UrlDownloader.

- src/PhpBrew/Command/DownloadCommand.php
- src/PhpBrew/Command/InstallCommand.php
- src/PhpBrew/Command/KnownCommand.php
- src/PhpBrew/Command/UpdateCommand.php
- src/PhpBrew/Downloader/UrlDownloader.php
- src/PhpBrew/ReleaseList.php
- tests/PhpBrew/Tasks/MakeTaskTest.php
There was an error with the tests execution. 
```
PHP Fatal error:  Class PhpBrew\Tasks\MakeTaskTestBuild contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PhpBrew\Buildable::isBuildable) in /home/travis/build/phpbrew/phpbrew/tests/PhpBrew/Tasks/MakeTaskTest.php on line 70
```
I've fixed it.
> CONNECT_TIMEOUT env variable and --connect_timeout option was added. Fatal Error during tests fixed

- shell/bashrc
The `-p' option means to use a default value for $PATH that is guaranteed to find all of the standard utilities
This also fixes the "env: node: No such file or directory" issue I mentioned at #506 (last comment)
> Add "-p" to $(command which phpbrew) to ensure a default PATH

- shell/bashrc
Fixes my PR #508 
As i mentioned at #506, OSX has a bug that makes it impossible to use the `command which phpbrew` solution. Here's a sample output on OSX with ZSH:
```shell
greensn0w@Mac  ~ 
❯ command which phpbrew
env: node: No such file or directory
```
With this PR we create a fallback from my solution (#508) to the one from @protomouse (#507)
This also works if phpbrew is in /usr/local/bin:
```shell
greensn0w@Mac  ~ 
❯ BIN=$(command -p which phpbrew 2> /dev/null || command which phpbrew)
greensn0w@Mac  ~ 
❯ echo $BIN
/usr/local/bin/phpbrew
```
Original idea by @marcioAlmada
> Fallback from `command -p` to `command`

- shell/bashrc
Before this change phpbrew clears your path and you can do nothing until you remove phpbrew's bashrc
> Extend $PATH instead of overwriting it

- index.html
Hello,
The `--svn` option of the `phpbrew known` command does not seem to exist anymore so I removed it.
> Removed reference to phpbrew known --svn

- shell/bashrc
There are two projects one of which has `.phpbrewrc` and the other doesn't (see the diagram below):
```
projects
|-- project1
|    |-- subdir
|    +-- .phpbrewrc (phpbrew use 5.4.44)
+-- project2
+-- subdir
```
For instance, the default PHP version is 5.6.12.
When entering project1, the php version changes to 5.4.44 and is kept during navigation:
```
↪  php -v
PHP 5.6.12
↪  cd projects/project1
↪  php -v
PHP 5.4.44
↪  cd subdir
↪  php -v
PHP 5.4.44
```
If enter project2 and choose a non-default php version, it's reset to default during navigation:
```
↪  php -v
PHP 5.6.12
↪  cd projects/project2
↪  phpbrew use 5.4.44
↪  php -v
PHP 5.4.44
↪  cd subdir
↪  php -v
PHP 5.6.12
```
> PHPBrew loads default configuration when navigating a subtree without .phpbrewrc

- src/PhpBrew/Command/CleanCommand.php
When using ```phpbrew clean --all php-x.y.z```, it looks for ```PhpBrew\Command\Utils``` which doesn’t exists.
```php 
Source directory /Users/Dharma/.phpbrew/build/php-5.6.12 found, deleting...
PHP Fatal error:  Class 'PhpBrew\Command\Utils' not found in phar:///Users/Dharma/bin/phpbrew/PhpBrew/Command/CleanCommand.php on line 2```
> Import of class PhpBrew\Utils in PhpBrew\Command\CleanCommand

- shell/bashrc
The bash prompt was never updated.
Before the change:
```bash
~ > me@debian [php:5.6.13-system]
$  phpbrew use 5.4.45
~ > me@debian [php:5.6.13-phpbrew]
$ 
```
After the change:
```bash
~ > me@debian [php:5.6.13-system]
$  phpbrew use 5.4.45
~ > me@debian [php:5.4.45-phpbrew]
$ 
```
```
>  Bash prompt, php version was never updated

- src/PhpBrew/CommandBuilder.php
- tests/PhpBrew/CommandBuilderTest.php
OSX's `tee` command do not accept long option formats like `--append`,
only their short forms. They probably needed to save the memory for some
huge background image, or were just willingly to break stuff (which is
more probably).
The bug occurs on OSX when installing a new PHP version using --stdout
option.
> Make `tee` call compatible with OSX

- src/PhpBrew/Command/SelfUpdateCommand.php
Sometimes, curl fails some reason.
like this
```bash
$ phpbrew self-update
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html
```
But the fail ignored, and overwrite `phpbrew` binary with failed file.
> Fix curl error handling when self updating

- README.md
MacOSX 10.11 (El Capitan) introduces extra security that won't let any user (even root) write to /usr, apart from /usr/local. This causes an "Operation not permitted" error when trying to move the executable to /usr/bin.
It seemed to work for me installing to /usr/local/bin, so I've changed the instructions. I don't know if they need changing anywhere else?
> Change suggested install location to /usr/local/bin

- shell/bashrc
Old code uses wrong way to transfer user arguments, I rewrite it to fit
bash way.
See #618
> Let user pass additional arguments to php-fpm

- shell/bashrc
Hi,
when I was started terminal and I just run `echo $PATH`.
The PATH is displayed as follows.
```
/Users/kurotaky/.phpbrew/php/php-5.6.3/bin::/Users/kurotaky/.plenv/shims:/Users/kurotaky/.rbenv/shims:/Users/kurotaky/.rbenv/shims:/usr/local/Cellar/emacs/HEAD/bin:/Users/kurotaky/.rbenv/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/kurotaky/bin
```
Although there is no assigned path to $PHPBREW_BIN, that is connected.
but the empty pathname( like `::`) referred to the current directory in POSIX.
so I fixed problem, the phpbrew bin path is not connected when $PHPBREW_BIN is blank.
> Does not connect the phpbrew bin path when $PHPBREW_BIN is blank

- src/PhpBrew/VariantBuilder.php
When building with a variant which is included into one of virtual variants, the value of the former is ignored:
```shell
↪  phpbrew -d install --dryrun 5.6.16 +default +openssl=/usr/local/opt/openssl
```
As far as virtual variants do not provide any values by definition, they shouldn't override explicitly specified values:
```shell
↪  phpbrew -d install --dryrun 5.6.16 +default +openssl=/usr/local/opt/openssl
```
> Do not override explicitly specified values with the default from virtual variants

- src/PhpBrew/Command/AppCommand/GetCommand.php
- src/PhpBrew/Command/AppCommand/ListCommand.php
- src/PhpBrew/Command/DownloadCommand.php
- src/PhpBrew/Command/InstallCommand.php
- src/PhpBrew/Command/UpdateCommand.php
- src/PhpBrew/Downloader/BaseDownloader.php
- src/PhpBrew/Downloader/CurlCommandDownloader.php
- src/PhpBrew/Downloader/CurlExtensionDownloader.php
- src/PhpBrew/Downloader/DownloadFactory.php
- src/PhpBrew/Downloader/Factory.php
- src/PhpBrew/Downloader/FileFunctionDownloader.php
- src/PhpBrew/Downloader/UrlDownloader.php
- src/PhpBrew/Downloader/WgetCommandDownloader.php
- src/PhpBrew/Extension/ExtensionDownloader.php
- src/PhpBrew/ReleaseList.php
- src/PhpBrew/Tasks/DownloadTask.php
- tests/PhpBrew/Downloader/DownloaderTest.php
this pr includes following features:
1. refactor `PhpBrew\Downloader\UrlDownloader`, use `PhpBrew\Downloader\Factory` and `PhpBrew\Downloader\BaseDownloader` instead. I have provided curl extension / curl command / wget command / pure php function (`file_get_contents`)
2. options `http-proxy`, `http-proxy-auth`, `connect-timeout` now supports both curl extension and pure php function
3. add option `downloader` to choose which downloader to use. (default: curl extension > pure php functon > wget command > curl command)
4. refactor `UpdateCommand`, `DownloadCommand`, `InstallCommand`, `GetCommand` to the new downloader, so all of these commands now support all the above options
5. the test case for new downloaders is `PhpBrew\Downloader\DownloaderTest`, but I haven't add it to phpunit.xml …
> refactor downloading related part ( #571 )

- src/PhpBrew/VariantParser.php
- tests/PhpBrew/VariantParserTest.php
Because the dot character is prohibited in unix-like filesystem, Also
Homebrew the most popular package manager in OS X that install package
in /usr/local/Cellar, If we prefer use keg-only pkgs to link with PHP
(for example: openssl). We have face the problem that user value can't
contains dot characters. This changes against this issue.
> Allow user value of variants contains dot character

- shell/phpbrew.fish
That is breaking the phpbrew support in fish shell.
> Proper redirect to STDERR for Fish shell

- src/PhpBrew/Tasks/ExtractTask.php
Hi! Recently I stuck with the problem:
```
PHP Catchable fatal error:  Object of class SplFileInfo could not be converted to boolean in /tmp/phpbrew/src/PhpBrew/Tasks/ExtractTask.php on line 22
PHP Stack trace:
PHP   1. {main}() /tmp/phpbrew/bin/phpbrew:0
PHP   2. CLIFramework\Application->run() /tmp/phpbrew/bin/phpbrew:21
PHP   3. CLIFramework\CommandBase->executeWrapper() /tmp/phpbrew/vendor/corneltek/cliframework/src/Application.php:398
PHP   4. call_user_func_array() /tmp/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php:845
PHP   5. PhpBrew\Command\InstallCommand->execute() /tmp/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php:845
PHP   6. PhpBrew\Tasks\ExtractTask->extract() /tmp/phpbrew/src/PhpBrew/Command/InstallCommand.php:336
```
So here really tiny fix :)
>  Object of class SplFileInfo could not be converted to boolean

- src/PhpBrew/Command/KnownCommand.php
this pr includes following changes:
1. if local release file contains old versions (versions below 5.3), `phpbrew known` will list version 5.1 and 5.0. the pr fix this bug
2. when local release file exists and doesn't contain old versions, `phpbrew known --old` doesn't work. the pr fix this bug ( #526 ) as well
3. add warning when --old present as phpbrew need at least 5.3 to run
4. add message about the change time of local release file.
> fix issues about known command

- shell/bashrc
As long as `$curr_dir` is not `cd`'ed into anymore, we use relative path for .phpbrew lookup and sourcing.
> Fixed .phpbrew lookup in parent directories (fixes #775)

- src/PhpBrew/VariantBuilder.php
PhpBrew fails to detect MySQL socket on Ubuntu. Even if it existed, it wouldn't be used because it corresponds to `$paths[5]`, not to `$paths[0]`.
> Use correct path for MySQL socket on Ubuntu. $paths[0] doesn't work, since array_filter() preserves indices. No need to check existence of all files.

- src/PhpBrew/AppStore.php
The `psysh` command is much like `ipython`, works perfectly for interactively running code and debugging.
source: http://psysh.org/
> Adds psysh.org's php REPL tool

- src/PhpBrew/VariantBuilder.php
When installing PHP on Ubuntu, it's expected that phpbrew automatically appends `--with-libdir=lib/x86_64-linux-gnu` to the configure command. This feature is broken since e93f221:
```
↪  file /usr/lib/x86_64-linux-gnu/
/usr/lib/x86_64-linux-gnu/: directory
↪  phpbrew --debug install --dryrun 5.6.26
./configure '--cache-file='\''/home/morozov/.phpbrew/cache/config.cache'\''' '--prefix=/home/morozov/.phpbrew/php/php-5.6.26' '--with-config-file-path=/home/morozov/.phpbrew/php/php-5.6.26/etc' '--with-config-file-scan-dir=/home/morozov/.phpbrew/php/php-5.6.26/var/db' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/usr' '--enable-bcmath' '--with-bz2=/usr' '--enable-calendar' '--enable-cli' '--enable-ctype' …
```
> Fixed automatic detection of --with-libdir

- src/PhpBrew/VersionDslParser.php
- tests/PhpBrew/VersionDslParserTest.php
When installing PHP from a github tag, the resulting version has double php- prefix:
```
↪  phpbrew --debug install --dryrun github:php/php-src@php-7.1.0RC3
To use the newly built PHP, try the line(s) below:
$ phpbrew use php-php-7.1.0RC3
Or you can use switch command to switch your default php to php-php-7.1.0RC3:
$ phpbrew switch php-php-7.1.0RC3
Enjoy!
```
Despite it can be worked around by means of using version alias like `as php-7.1.0RC3`, it would be more intuitive to have a single prefix out of the box.
> Double php- when installing from github tag

- src/PhpBrew/Command/UseCommand.php
- tests/PhpBrew/Command/PathCommandTest.php
When I start typing a PHP version without the php- prefix, the version doesn't get completed:
```
↪  phpbrew use 5[tab][tab]
```
However, there's a few 5.x versions installed:
```
↪  phpbrew list
php-7.1.0RC5   
* php-7.0.11     
php-5.6.27     
php-5.6.26-libmysqlclient
php-5.5.38     
php-5.4.45     
php-5.3.29     
```
It's especially annoying, given that the `use` command allows [omitting the "php-" prefix](https://github.com/morozov/phpbrew/blob/c9cff47797f560aef126b8d2b1a65daa7cd5590b/shell/bashrc#L137-L137) for standard versions.
In order to get the completion work, one has to not type any prefix and let the completion script add "php-":
```
↪  phpbrew use [tab][tab]php-[5][tab].[tab][tab]
php-5.3.29                 php-5.5.38                 php-5.6.27
php-5.4.45 …
```
> Prefix completion only works with php- prefix

- shell/phpbrew.fish
Provided phpbrew.fish uses incorrect syntax for `if` command.
Example (using fish shell):
```
$ phpbrew purge php-7.1.0
No command 'then' found, did you mean:
Command 'the' from package 'the' (universe)
Command 'when' from package 'when' (universe)
Command 'thin' from package 'thin' (universe)
then: command not found
~/.phpbrew/phpbrew.fish (line 13):     if [ -d $_PHP_BIN_PATH ]; then
^
in function “__phpbrew_remove_purge”
called on line 296 of file ~/.phpbrew/phpbrew.fish
with parameter list “php-7.1.0 purge”
in function “phpbrew”
called on standard input
with parameter list “purge php-7.1.0”
php version: php-7.1.0 is removed and purged.
```
> Fix wrong `if` fish syntax

- shell/bashrc
- src/PhpBrew/BuildFinder.php
When switching to a release version, say 5.6.26, one can omit or preserve the php- prefix, and both `phpbrew use 5.6.26` and `phpbrew use php-5.6.26` will work as expected. While in case of a non-release version, say 7.1.0RC3, only the approach with the prefix works:
```
↪  phpbrew list
php-7.1.0RC3   
* php-7.0.11     
php-5.6.26     
php-5.5.38     
php-5.4.45     
php-5.3.29     
↪  phpbrew use 5.6.26
↪  php --version
PHP 5.6.26 (cli) (built: Sep 28 2016 14:10:31) 
↪  phpbrew use 7.1.0RC3
php version: 7.1.0RC3 not exists.
↪  phpbrew use php-7.1.0RC3
↪  php --version
PHP 7.1.0RC3 (cli) (built: Oct  3 2016 16:32:50) ( NTS )
```
> `phpbrew use` doesn't work for non-release versions

- shell/bashrc
Fixes #782 introduced by #680.
> Do not break too early and let the needed break procedure to be executed on the next iteration.

- README.ja.md
- README.md
This PR updates the Japanese and English README files.
Though minor, installation following current instructions will fail on systems running OS X 10.11 (El Capitan) or macOS 10.12 (Sierra).
This is due to a newer feature of the OS, called [System Integrity Protection], a security measure which prevents even root-level access to a number of directories, including `/usr/bin`.
The Portuguese README has already been updated accounting for this.
[System Integrity Protection]: https://support.apple.com/en-us/HT204899
> Update Japanese and English READMEs

- .travis.yml
- tests/PhpBrew/BuildRegisterTest.php
- tests/PhpBrew/BuildSettings/BuildSettingsTest.php
- tests/PhpBrew/BuildSettings/DefaultBuildSettingsTest.php
- tests/PhpBrew/BuildTest.php
- tests/PhpBrew/CommandBuilderTest.php
- tests/PhpBrew/ConfigTest.php
- tests/PhpBrew/Distribution/DistributionUrlPolicyTest.php
- tests/PhpBrew/Downloader/DownloaderTest.php
- tests/PhpBrew/Extension/ExtensionInstallerTest.php
- tests/PhpBrew/Extension/ExtensionManagerTest.php
- tests/PhpBrew/Extension/ExtensionTest.php
- tests/PhpBrew/Extension/Provider/RepositoryDslParserTest.php
- tests/PhpBrew/MachineTest.php
- tests/PhpBrew/PatchUtilsTest.php
- tests/PhpBrew/Platform/Linux/CentOSTest.php
- tests/PhpBrew/Platform/Linux/DebianTest.php
- tests/PhpBrew/Platform/Linux/UnknownDistributionTest.php
- tests/PhpBrew/Platform/LinuxTest.php
- tests/PhpBrew/Platform/MacTest.php
- tests/PhpBrew/Platform/PlatformInfoTest.php
- tests/PhpBrew/Platform/UnixLikeHardwareTest.php
- tests/PhpBrew/Platform/UnknownPlatformTest.php
- tests/PhpBrew/ReleaseListTest.php
- tests/PhpBrew/Tasks/MakeTaskTest.php
- tests/PhpBrew/UtilsTest.php
- tests/PhpBrew/VariantBuilderTest.php
- tests/PhpBrew/VariantParserTest.php
- tests/PhpBrew/VersionDslParserTest.php
- tests/PhpBrew/VersionTest.php
fix #855 
the test for cliframework still needs to be updated otherwise php 7.2 will broke the ci test since phpunit 5.7 won't support php 7.2.
> fix travis-ci test 

- shell/phpbrew.fish
error message
[: Expected a combining operator like '-a' at index 1”
in fish `set code (phpbrew env xxx)` set $code as an array instead of
multiline text (see fish-shell/fish-shell#159)
thus `eval $code` become
```
eval "export A=B export C=D"
```
instead of
```
eval "export A=B\
export C=D"
```
(another problem is the export polyfill function is not robust)
this commit fix that replacing newline with semicol, makes $code a
valid one-liner
```
eval "export A=B;export C=D"
```
also set the exit status (`__phpbrew_set_path ` somehow return nonzero
status)
> fix error in fishshell running `phpbrew use xxx`

- shell/bashrc
Steps to reproduce:
1. Install PHP 7.2.0-dev with FPM support: 
```
phpbrew install github:php/php-src@master as php-7.2.0 +default +fpm
```
2. Start the FPM service:
```
phpbrew fpm start
```
Expected behavior: the service starts.
Actual behavior:
```
Starting php-fpm...
Usage: php-fpm [-n] [-e] [-h] [-i] [-m] [-v] [-t] [-p <prefix>] [-g <pid>] [-c <file>] [-d foo[=bar]] [-y <file>] [-D] [-F [-O]]
-c <path>|<file> Look for php.ini file in this directory
-n               No php.ini file will be used
-d foo[=bar]     Define INI entry foo with value 'bar'
-e               Generate extended information for debugger/profiler
-h               This help
-i               PHP information
-m               Show compiled in modules
-v               Version number
-p, --prefix <dir>
Specify …
```
> phpbrew fpm {start|stop} fails on PHP 7.2.0-dev

- src/PhpBrew/Command/ExtensionCommand/InstallCommand.php
While [PHP 5.6 only receives security updates](http://php.net/supported-versions.php) and [PHP 7 overall now represents over 50%](https://seld.be/notes/php-versions-stats-2017-1-edition) of installations, the warning in the question seems no more relevant.
> Removed the warning when installing extensions for PHP 7

- src/PhpBrew/Command/ExtensionCommand/InstallCommand.php
Currently, it's impossible to install an extension from GitHub without explicitly specifying the version:
```
$ phpbrew ext install github:nikic/php-ast.git
Downloading https://github.com/nikic/php-ast/archive/stable.tar.gz via curl extension
Redirecting to https://codeload.github.com/nikic/php-ast/tar.gz/stable
PHP Fatal error:  Uncaught CurlKit\CurlException: The requested URL returned error: 404 Not Found at [https://codeload.github.com/nikic/php-ast/tar.gz/stable:The requested URL returned error: 404 Not Found] in vendor/corneltek/curlkit/src/CurlKit/CurlDownloader.php:153
```
The generated URL (https://codeload.github.com/nikic/php-ast/tar.gz/stable) is incorrect, it should be https://codeload.github.com/nikic/php-ast/tar.gz/master.
The default extension configuration should not …
> Fix installing extension from GitHub

- shell/bashrc
- src/PhpBrew/Command/PurgeCommand.php
As an end user, I'd like to be able to purge multiple PHP builds using a single `phpbrew purge` command in a way similar to `rm file1 file2` or `git branch -d branch1 branch2`. Currently, all arguments following the build to be purged are ignored without any feedback.
The provided patch makes the `phpbrew purge` command accept multiple `installed php` arguments. Its implementation in Bash has been cleaned up to not handle the `remove` command which is implemented in `RemoveCommand`.
> Implemented purging multiple PHP builds at a time

- CHANGES.md
- shell/bashrc
- src/PhpBrew/Command/EachCommand.php
Currently, the `each` command only allows running only a subset PhpBrew commands (see #559, #800). It's reimplemented on the shell level to support running shell commands instead.
> Reimplemented the each command

- src/PhpBrew/Downloader/WgetCommandDownloader.php
The condition was inverted.
When no http-proxy-auth was given, the wget was using authentication which resulted in broken http_proxy option such as:
-e http_proxy=@http://my.proxy:8080
> fix: Inverted condition for option http-proxy-auth

- src/PhpBrew/VariantBuilder.php
When building PHP `+gd` without the prefix specified, the `gd` extension is not built:
```
$ phpbrew --debug install --dryrun 7.1.9 as test-gd1 +neutral +gd
--------8<--------
./configure \
'--cache-file=/home/morozov/.phpbrew/cache/config.cache' \
'--prefix=/home/morozov/.phpbrew/php/test' \
'--with-config-file-path=/home/morozov/.phpbrew/php/test/etc' \
'--with-config-file-scan-dir=/home/morozov/.phpbrew/php/test/var/db' \
'--with-libdir=lib/x86_64-linux-gnu' \
'--enable-gd-native-ttf' \
'--with-jpeg-dir=/usr' \
'--with-png-dir=/usr' \
'--with-freetype-dir=/usr' \
'--enable-dom' \
'--enable-libxml' \
'--enable-simplexml' \
'--enable-xml' \
'--enable-xmlreader' \
'--enable-xmlwriter' \
'--with-xsl' \
'--with-libxml-dir=/usr' \
'--enable-opcache' \ …
```
> Use bundled GD if no prefix provided

- src/PhpBrew/Build.php
- src/PhpBrew/Tasks/ConfigureTask.php
- src/PhpBrew/VariantBuilder.php
Additionally, modified the default PEAR path from `$BUILD_DIR/lib/php` to `$BUILD_DIR/lib/php/pear` for cleaner directory layout.
The current layout looks a bit messy:
```
├── Archive
├── build
├── Console
├── data
├── doc
├── extensions
├── OS
├── PEAR
├── pearcmd.php
├── PEAR.php
├── peclcmd.php
├── Structures
├── System.php
├── test
└── XML
```
The _extensions_ and _build_ directory do not belong to PEAR but are mixed with its top-level packages. Moving PEAR into its own directory makes the layout cleaner:
```
├── build
├── extensions
└── pear
```
It also helps avoid potential conflicts between top-level PEAR packages and internal PHP resources.
> Moved --with-pear to the pear variant

- src/PhpBrew/VariantBuilder.php
Currently, if the variant builder cannot detect prefix for cURL, it silently drops the variant (note the absence of `--with-curl` in the resulting `./configure` command):
```
↪  phpbrew --debug install --dryrun 7.1.9 +neutral +curl
./configure \
'--cache-file=/home/morozov/.phpbrew/cache/config.cache' \
'--prefix=/home/morozov/.phpbrew/php/php-7.1.9' \
'--with-config-file-path=/home/morozov/.phpbrew/php/php-7.1.9/etc' \
'--with-config-file-scan-dir=/home/morozov/.phpbrew/php/php-7.1.9/var/db' \
'--with-libdir=lib/x86_64-linux-gnu' \
'--enable-dom' \
'--enable-libxml' \
'--enable-simplexml' \
'--enable-xml' \
'--enable-xmlreader' \
'--enable-xmlwriter' \
'--with-xsl' \
'--with-libxml-dir=/usr' \
'--enable-opcache' \
>> /home/morozov/.phpbrew/build/php-7.1.9/build.log 2>&1
```
If …
> Fixed cURL extension being silently dropped if dependencies not found

- src/PhpBrew/Command/InstallCommand.php
- src/PhpBrew/VersionDslParser.php
- tests/PhpBrew/VersionDslParserTest.php
Pre-release versions can be installed similarly to the release ones, e.g. `phpbrew install 7.2.0RC3`.
> Installation of pre-release versions using the same syntax as the release ones

- .travis.yml
- composer.lock
After the revert of `composer.lock` in #912, it's impossible to install PHPBrew with empty cache and vendor directory:
```
↪  composer install 
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Package operations: 27 installs, 0 updates, 0 removals
- Installing symfony/finder (v2.8.5): Loading from cache
- Installing symfony/polyfill-apcu (v1.1.1): Loading from cache
- Installing symfony/class-loader (v2.8.5): Loading from cache
- Installing pimple/pimple (v3.0.2): Loading from cache
- Installing corneltek/universal (1.7.2): Downloading (failed)    Failed to download …
```
> Rebuit composer.lock

- src/PhpBrew/VariantBuilder.php
Fixes #919. Replaced `$output` with `$prefix`, use `printf()` for cleaner error message.
> PHP Notice: Undefined variable: output in .../VariantBuilder.php on line 243

- .travis.yml
- composer.json
- composer.lock
In the case when the project is not installed, calling `composer require` seems to update all dependencies and install them. Instead, add explicit requirement for PHPUnit (it's also useful to have it during development) and lock it at the version compatible with PHP 5.3.
Fixes #928.
> Added explicit development requirement of PHPUnit

- composer.lock
- src/PhpBrew/Command/UseCommand.php
- src/PhpBrew/Config.php
- tests/PhpBrew/Command/InstallCommandTest.php
Prior to fixing c9s/CLIFramework#106, even if the command argument was invalid, it didn't cause the command to fail. After having this fixed, `InstallCommandTest::testUseCommand()` started failing. The `UseCommand` declared that it expected a non-prefixed with php- version name while it expected the build name instead. It's fine since it only provides completion info but not the implementation.
The `testUseCommand()` is reworked to `testEnvCommand()` because this is what gets invoked from the shell wrapper when a user types `phpbrew use`.
Fixes #822.
> Fail on invalid argument

- src/PhpBrew/Console.php
- src/PhpBrew/Testing/CommandTestCase.php
- src/PhpBrew/Utils.php
According to #824, the issue happens outside of PHPBrew and is by design. PHPBrew itself doesn't try to change anything in protected directories.
According to comments in #879, the warning may be confusing since it's displayed for every command and therefore can be misinterpreted as the cause of any issue.
Fixes #879.
> Removed the warning about rootless mode in macOS

- src/PhpBrew/Downloader/BaseDownloader.php
One of the thrown exceptions inside the "download" function was being referenced wrongly.
> Fixing throw of RuntimeException in BaseDownloader

- shell/bashrc
With the patch applied:
```
↪ export PATH="/a /b /c :$PATH"
↪ phpbrew use 5.3.29
↪ echo $PATH
/home/morozov/.phpbrew/php/php-5.3.29/bin:/home/morozov/.phpbrew/bin:/a /b /c :./vendor/bin:~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
↪ phpbrew use 7.1.11
↪ echo $PATH
/home/morozov/.phpbrew/php/php-7.1.11/bin:/home/morozov/.phpbrew/bin:/a /b /c :./vendor/bin:~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```
Fixes #823.
> PHPBrew is breaking PATH with spaces in WSL and probably everywhere else

- src/PhpBrew/VariantBuilder.php
An attempt to `phpbrew install 7.2.2 +gd` produces:
```
configure: WARNING: unrecognized options: --enable-gd-native-ttf
```
According to the [manual](http://php.net/manual/en/image.installation.php), the `--enable-gd-native-ttf` switch is effectless as of PHP 5.5.0 and removed as of PHP 7.2.0.
> Made --enable-gd-native-ttf conditional depending on the PHP version

- src/PhpBrew/VariantBuilder.php
PHP Notice:  Undefined variable: output in phar:///usr/local/bin/phpbrew/src/PhpBrew/VariantBuilder.php on line 321
> Fix Undefined variable: output

- shell/bashrc
If `PHPBREW_RC_ENABLE` is set, we look for `.phpbrewrc` after **EVERY** command, even though we only need to look for it _when the current directory changes_. That `trap` call may be needed in bash, but zsh provides a hook mechanism for various shell events, including changing directory.
This PR makes use of that hook mechanism to look for .`phpbrewrc` **ONLY** when the current directory changes. This affects only zsh users.
- Looks for `.phpbrewrc` **ONLY** when changing directories, instead of after **EVERY** command.
- Plays nice with other tools who might have included their own functions in the same `cd` hook.
- Integrates more seamlessly into a zsh ecosystem.
- Benefits only zsh users (at least for now).
You can check http://zsh.sourceforge.net/Doc/Release/Functions.html#Hook-Functio …
> Use zsh chpwd hooks to look for .phpbrewrc instead of trap call

- src/PhpBrew/VariantBuilder.php
An attempt to `phpbrew install 7.2.2 +default` produces:
```
configure: WARNING: unrecognized options: --with-mcrypt
```
The `mcrypt` extension has been deprecated in PHP 7.1 and removed in PHP 7.2. We could add some conditional logic to detect if `mcrypt` is available in the PHP version being built and still enable it by default if it's available, but I believe it's better to just remove it from the default variant.
> Removed the mcrypt extension from the default variant

- src/PhpBrew/Command/FpmCommand.php
- src/PhpBrew/Command/FpmCommand/RestartCommand.php
- src/PhpBrew/Command/FpmCommand/StartCommand.php
- src/PhpBrew/Command/FpmCommand/StopCommand.php
- src/PhpBrew/Command/SwitchCommand.php
- src/PhpBrew/Command/VirtualCommand.php
- tests/PhpBrew/Command/DownloadCommandTest.php
- tests/PhpBrew/Command/InstallCommandTest.php
- tests/PhpBrew/Extension/KnownCommandTest.php
Additionally,
1. Removed unused imports in all `fpm` subcommands.
2. Made all `fpm` subcommands explicitly extend `VirtualCommand`.
3. Made `VirtualCommand::execute()` `final` in order to make sure the extending commands do not implement any other handling (this is the purpose of virtual command).
4. Cleaned up imports and annotations in `VirtualCommand`.
> Added the "fpm restart" command to shell completion

- src/PhpBrew/AppStore.php
The old url `https://git.io/psysh` leads to an old url which no longer contains the latest file.
This change uses the url from the website `https://psysh.org/psysh`.
Solves #1013
> Fix psysh download url

- src/PhpBrew/Extension/Provider/BitbucketProvider.php
This is supposed to fix build failures like [#552268742](https://travis-ci.org/phpbrew/phpbrew/jobs/552268742#L478).
> Switched to Bitbucket API v2.0 since v1.0 is no longer supported

- shell/bashrc
- shell/phpbrew.fish
1. Implemented the same logic of handling `.phpbrewrc` files in Fish as currently implemented in Bash and ZSH.
2. Fixed handling filesystem boundaries in Bash (the filesystem check should have been done against `$curr_dir`, not the current directory in the shell).
3. Fixed a syntax error in `phpbrew.fish`.
> Fixed handing of .phpbrewrc in Fish

- src/PhpBrew/PrefixFinder.php
- src/PhpBrew/PrefixFinder/BrewPrefixFinder.php
- src/PhpBrew/PrefixFinder/IncludePrefixFinder.php
- src/PhpBrew/Utils.php
- src/PhpBrew/VariantBuilder.php
Additionally, introduced the Include and Brew prefix finders to reduce the amount of boilerplate code.
Fixes #1020.
> Use --enable-gd instead of --with-gd for PHP 7.4

- src/PhpBrew/VariantBuilder.php
Unlike `--with-pcre-dir`, `--with-external-pcre` does not accept a prefix and if enabled, will rely on `pkg-config` internally. If a user wants to build the extension with an external library, they will have to specify `--with-external-pcre`. There's nothing PHPBrew can do in this case.
Fixes #1022.
> Do not pass --with-pcre-dir to PHP 7.4

- src/PhpBrew/PrefixFinder/LibPrefixFinder.php
- src/PhpBrew/PrefixFinder/PkgConfigPrefixFinder.php
- src/PhpBrew/Utils.php
- src/PhpBrew/VariantBuilder.php
PHP 7.4 no longer supports `--with-libxml-dir` (https://github.com/php/php-src/pull/4037).
> Do not pass --with-libxml-dir to PHP 7.4

- src/PhpBrew/VariantBuilder.php
PHP 7.4 no longer supports `--with-icu-dir` (https://github.com/php/php-src/pull/3701).
> Do not pass --with-icu-dir to PHP 7.4

- src/PhpBrew/Patches/FreeTypePatch.php
- src/PhpBrew/Tasks/BeforeConfigureTask.php
- src/PhpBrew/Tasks/BuildConfTask.php
1. Patch `ext/gd` with the [patch](https://git.archlinux.org/svntogit/packages.git/tree/trunk/freetype.patch?h=packages/php) from Arch Linux.
2. Extract `./buildconf --force` into a reusable component.
Fixes #1033.
> Patch ext/gd in PHP < 7.4 for compatibility with newer Debian distros

- shell/phpbrew.fish
When switching PHP versions using Fish, `phpbrew switch` exits with a non-zero code even on success:
```
$ phpbrew list
php-7.4.0RC2
* php-7.3.10
$ phpbrew switch 7.4.0RC2
$ echo $status
1
$ phpbrew list
* php-7.4.0RC2   
php-7.3.10     
$ php -v
PHP 7.4.0RC2 (cli) (built: Sep 21 2019 15:26:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0-dev, Copyright (c) Zend Technologies
with Zend OPcache v7.4.0RC2, Copyright (c), by Zend Technologies
with Xdebug v3.0.0-dev, Copyright (c) 2002-2019, by Derick Rethans
```
> Fixed the switch subcommand exit status on Fish

- src/PhpBrew/Patches/PHP56WithOpenSSL11Patch.php
- src/PhpBrew/Tasks/AfterConfigureTask.php
The API of OpenSSL has changed from 0.10 to 0.11. This makes it difficult to run PHP 5 on an updated system. The patch is from https://github.com/php/php-src/pull/2667.
Note that the patch only works for PHP 5.6.31 or higher. While not ideal, being able to install the last (released) PHP5 version will be sufficient for most.
> Apply patch to PHP 5.6 for running with OpenSSL 0.11

- composer.json
- composer.lock
Under certain circumstances, the downloader may use HTTP/2, in which case the download will fail:
```
$ phpbrew install 7.1.31
===> phpbrew will now build 7.1.31
---> Parsing variants from command arguments '+curl +default +fpm +gd +gmp +iconv +intl +ldap +mysql +sqlite +soap'
===> Loading and resolving variants...
Downloading https://secure.php.net/get/php-7.1.31.tar.bz2/from/this/mirror via curl extension
Fatal error: Uncaught CurlKit\CurlException:  at [The Location header can not be found: HTTP/2 302 
server: myracloud
date: Sun, 11 Aug 2019 23:38:06 GMT
content-type: text/html; charset=utf-8
content-language: en
x-frame-options: SAMEORIGIN
set-cookie: COUNTRY=NA%2C82.199.157.54; expires=Sun, 18-Aug-2019 23:38:06 GMT; Max-Age=604800; path=/; domain=.php.net
x-php-load: 0.12, 0.13, 0.1 …
```
> Updated corneltek/curlkit to the latest version containing c9s/CurlKit#6

- src/PhpBrew/Tasks/ExtractTask.php
1. Create a temporary directory only if needed.
2. Remove it in the class destructor.
Fixes #1056.
> Clean up the temporary directory used during a package extraction

- completion/bash/_phpbrew
- completion/zsh/_phpbrew
- src/PhpBrew/AppStore.php
[The PHP Coding Standards Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) (PHP CS Fixer) tool fixes your code to follow standards; whether you want to follow PHP coding standards as defined in the PSR-1, PSR-2, etc., or other community driven ones like the Symfony one. You can also define your (teams) style through configuration.
> Add 'php-cs-fixer' to the AppStore

- shell/bashrc
- shell/phpbrew.fish
- src/PhpBrew/BuildFinder.php
Similarly to #798, added support for `-dev` versions e.g. `phpbrew use 8.0.0-dev`.
> Allow to reference PHP -dev builds without using the php- prefix

- src/PhpBrew/PatchKit/RegExpPatchRule.php
> Use the proper order of arguments when calling implode()

- composer.json
- composer.lock
Pulling in the following changes: https://github.com/c9s/CLIFramework/compare/df9139a84c8aee2cd6952632c31bdfab4855f22f...2650a53433854d43b91955e8f967c62ce07869d7.
Specifically, it includes the fixes for https://github.com/c9s/CLIFramework/issues/106 and https://github.com/c9s/CLIFramework/issues/108.
Fixes https://github.com/phpbrew/phpbrew/issues/822.
Not upgrading to a release due to incompatibility with PHP 5.3.
> Updated the CLIFRamework dependency constraint

- composer.json
- composer.lock
- https://github.com/c9s/CurlKit/compare/9e85064c3a8a642292a8f6122792d2b5b24f7b02...1.0.11
- https://github.com/phpbrew/PEARX/compare/2d361b36e9230390701fd7db46eecd3b13527e25...1.3.4
> Updated CurlKit and PEARX dependency constraints to the latest stable versions

- src/PhpBrew/Patches/PHP56WithOpenSSL11Patch.php
Fixed match() function for PHP56WithOpenSSL11Patch.php.
Reference: https://github.com/phpbrew/phpbrew/pull/1041
> Fix match() function for PHP56WithOpenSSL11Patch

- phpunit.xml.dist
- tests/PhpBrew/VariantBuilderTest.php
1. Removed test coverage and logging enabled by default.
2. Validated the configuration against the XSD and removed redundant parameters.
3. Removed the breakdown by test suites. All tests are important, slow tests will be moved out later.
4. Fixed accidental failures `VariantBuilderTest`. Depending on the environment, the configure options may or may not have the path specified and it's okay and should not be enforced by the test.
5. Got rid of custom assertions like `ok()`. They are too unspecific. The rest will have to go later.
> Cleaned up the test suite a bit

- .travis.yml
- composer.json
- composer.lock
This is needed in order to make sure we won't update locked dependencies to the versions that are not supported by the oldest supported PHP version while not using this verion during an update. Although, on CI we want to use the latest PHPUnit version that is supports the current PHP version.
The PHP 5.3.9 is used since this is the oldest PHP version that is supported by the currently locked dependencies (symfony/* specifically).
> Enforced PHP version in Composer configuration

- .travis.yml
- composer.json
- composer.lock
Additionally, bumped locked symfony/* components to v2.8.52.
> Replaced abandoned satooshi/php-coveralls with php-coveralls/php-coveralls

- composer.json
- composer.lock
1. symfony/process is not used anywhere.
2. corneltek/universal is only used as a transient dependency.
> Removed unused dependencies

- README.cn.md
- README.ja.md
- README.md
- README.pt-br.md
- completion/bash/_phpbrew
- completion/zsh/_phpbrew
- shell/phpbrew.fish
- src/PhpBrew/Command/SelfUpdateCommand.php
Having the built PHAR in the source tree is annoying since IDEs pick up its content and use for static analysis, completion, etc. It's not part of the source tree, cannot be merged, blamed, yadda yadda yadda.
As of now, GitHub supports [linking to the latest release](https://help.github.com/en/github/administering-a-repository/linking-to-releases#linking-to-the-latest-release) which we can leverage instead.
**TODO:**
> When doing a self-update, download the file from GitHub releases instead of the repository

- src/PhpBrew/Command/InstallCommand.php
- src/PhpBrew/VariantParser.php
- tests/PhpBrew/VariantParserTest.php
The syntax that allows specifying multiple variants in one CLI argument has the following downsides:
1. It doesn't solve any real problem. The same configuration can be expressed using one variant per argument.
2. The resulting syntax is ambiguous. What does `+openssl=/usr-mysql` mean? Is `-mysql` part of the `openssl` prefix or it disables the `mysql` variant?
```php
var_dump(
VariantParser::parseCommandArguments(array('+openssl=/usr-mysql'))
);
/*
array(3) {
'enabled_variants' =>
array(1) {
'openssl' =>
string(10) "/usr-mysql"
}
'disabled_variants' =>
array(0) {
}
'extra_options' =>
array(0) {
}
}
*/
```
3. The parser is unnecessarily complex and doesn't handle syntax errors properly:
```php
var_dump(
VariantParser::parseCommandArguments(array('+mysql followed+ by- *garbage'))
);
/* …
```
> Deprecated the usage of multiple variants in one command line argument

- src/PhpBrew/Patches/FreeTypePatch.php
- src/PhpBrew/Patches/PHP53Patch.php
- src/PhpBrew/Patches/PHP56WithOpenSSL11Patch.php
After #1093 was merged, the reported code coverage dropped from ~40% to 6%. This is because the PHP source patches are now part of the patch classes and they count towards the lines of code subject to coverage. They should be excluded from coverage to not distort the statistics.
> Fixed code coverage

- shell/phpbrew.fish
The `each` subcommand is currently not implemented in Fish:
```
$ echo $SHELL
/usr/bin/fish
$ phpbrew each php -v
Exception: You should not see this. If you see this, it means you didn't load the ~/.phpbrew/bashrc script. Please check if bashrc is sourced in your shell.
```
> Implemented the each subcommand in Fish

- composer.json
- composer.lock
The dependency was added in #912 probably to prevent an upgrade to an incompatible version.
> Removed unnecessary top-level dependency on corneltek/class-template

- src/PhpBrew/BuildFinder.php
- src/PhpBrew/Command/CleanCommand.php
- src/PhpBrew/Command/CtagsCommand.php
- src/PhpBrew/Command/EnvCommand.php
- src/PhpBrew/Command/ListCommand.php
- src/PhpBrew/Command/PurgeCommand.php
- src/PhpBrew/Command/SwitchCommand.php
- src/PhpBrew/Command/UseCommand.php
- src/PhpBrew/Config.php
- tests/PhpBrew/Command/InstallCommandTest.php
Additionally:
1. Removed the `$stripPrefix` flag from `BuildFinder::findInstalledBuilds()`. Instead, introduced `BuildFinder::findInstalledVersions()`.
2. Removed `BuildFinder::findMatchedBuilds()`.
3. Replaced code usages: `Config::getInstalledPhpVersions()` → `BuildFinder::findInstalledBuilds()` (returns builds with the "php-" prefix); `BuildFinder::findInstalledBuilds()` or `BuildFinder::findMatchedBuilds()` → `BuildFinder::findInstalledVersions()` (returns versions without the "php-" prefix).
4. Removed the unnecessary exception from `BuildFinder::findInstalledBuilds()`. The non-existing php directory isn't a more exceptional situation than the empty directory (which doesn't result in an exception).
> Removed deprecated Config::getInstalledPhpVersions()

- src/PhpBrew/VariantBuilder.php
Sodium is part of the PHP core since 7.2.
See https://www.php.net/manual/en/sodium.installation.php
Added `sodium` to the `default` virtual variant.
> Added `sodium` as variant.

- bin/phpbrew
- completion/bash/_phpbrew
- completion/zsh/_phpbrew
- shell/bashrc
- shell/phpbrew.fish
- src/PhpBrew/Command/EnvCommand.php
- src/PhpBrew/Command/SystemCommand.php
- src/PhpBrew/Command/SystemOffCommand.php
- src/PhpBrew/Console.php
The full new feature is implemented in the first commit and then partially reverted to the deprecation mode in the second one.
**Migration path:**
1. Once upgraded, if a user uses PHPBrew with an old PHP version, PHPBrew will display a warning suggesting to set the system interpreter. In the deprecation mode, the `use` and `switch` commands will not have the intended PHP version constraints while `system` and `system-off` will. This will motivate the users to configure their environment as expected.
2. In the next minor release, we'll revert the deprecation layer and drop the support for the older PHP version. At this point, the users will be expected to have their environment configured.
**TODO:**
1. A new environment variable `PHPBREW_SYSTEM_PHP` has been introduced. If set, it must …
> Implemented the usage of the system PHP interpreter

- shell/bashrc
As of #1101, `phpbrew use` does not accept the arguments that don't start with "php-". E.g.:
```
$ phpbrew list
php-8.0.0-dev
* php-7.4.1
php-7.3.13
php-7.1.33
php-5.6.40
php-5.3.29
$ phpbrew use 5.3.29
PHP version 5.3.29 is not installed.
$ phpbrew use php-5.3.29
$ phpbrew use
Currently using php-5.3.29
```
The reason is that the moment when the vesion regular expression pattern was converted from a variable to a literal, it should have been unquoted.
> Fixed __phpbrew_normalize_build in Bash

- .prettyci.composer.json
- README.cn.md
- README.md
- src/PhpBrew/BuildFinder.php
- src/PhpBrew/VariantBuilder.php
- tests/PhpBrew/Patches/Apache2ModuleNamePatchTest.php
The reasons are:
1. Style-CI uses some non-standard engine and rules that currently don't support PSR-12.
2. Style-CI doesn't allow configuration via code stored in the repository.
3. PrettyCI supports PHP_CodeSniffer and custom standards like doctrine/coding-standards.
> Switched from Style-CI to PrettyCI

- completion/bash/_phpbrew
- completion/zsh/_phpbrew
- shell/phpbrew.fish
- src/PhpBrew/Command/UpdateCommand.php
The flag doesn't have any effect as of 442e7021450a69cc912a6f95119dc2320ab79cc4 but has been marked as deprecated only in the commit message.
> Removed the --official flag of the update command

- composer.json
- composer.lock
The update removes the unnecessary transient dependencies on [`corneltek/cachekit`](https://packagist.org/packages/corneltek/cachekit) and [`corneltek/serializerkit`](https://packagist.org/packages/corneltek/serializerkit).
> Updated the PEARX to 1.3.5

- src/PhpBrew/Build.php
- src/PhpBrew/Command/InstallCommand.php
- src/PhpBrew/VariantBuilder.php
I try to dig the source code and add `PKG_CONFIG_PATH` to build process, it makes easier for user when build php 7.4.
It is just  a proof of concept, for discussion only.
With the PR, you can build php 7.4, with the following command only, no more `export PKG_CONFIG_PATH=...`.
```bash
$ phpbrew --debug install --jobs "$(nproc)" 7.1.33 +default +dbs +dba +apxs2 +bz2="$(brew --prefix bzip2)" +zlib="$(brew --prefix zlib)" +ftp
```
But, there is a problem when build extensions, take `ftp` and `soap` for example.  You can install it with `phpbrew install 7.4.0 +default +ftp`, the build process will set the PKG_CONFIG_PATH for you.
But, with this PR, you still can't install extension by following command only.
```
phpbrew ext install ftp
phpbrew ext install soap
```
Because the current …
> Add PKG_CONFIG_PATH environment variables to phpbrew build process

- src/PhpBrew/VariantBuilder.php
Add homebrew dependency support for bz2 and iconv. Now, you don't need to do `+bz2=$(brew --prefix bz2)` and `+iconv=$(brew --prefix iconv)`, just `+bz2` and `+iconv` is enough.
But, this only works for `phpbrew install`, not for `phpbrew ext install`, you still need to assign prefix as before.
> Add homebrew support for bz2 and iconv

- README.cn.md
- README.ja.md
- README.md
- README.pt-br.md
- src/PhpBrew/Build.php
- src/PhpBrew/BuildSettings/BuildSettings.php
- src/PhpBrew/Command/InstallCommand.php
- src/PhpBrew/ConfigureParameters.php
- src/PhpBrew/PrefixFinder/UserProvidedPrefix.php
- src/PhpBrew/Tasks/Apxs2CheckTask.php
- src/PhpBrew/Tasks/BeforeConfigureTask.php
- src/PhpBrew/Tasks/ConfigureTask.php
- src/PhpBrew/VariantBuilder.php
- src/PhpBrew/VariantParser.php
- tests/PhpBrew/BuildSettings/BuildSettingsTest.php
- tests/PhpBrew/BuildTest.php
- tests/PhpBrew/ConfigureParametersTest.php
- tests/PhpBrew/Patches/Apache2ModuleNamePatchTest.php
- tests/PhpBrew/Patches/IntlWith64bitPatchTest.php
- tests/PhpBrew/Patches/OpenSSLDSOPatchTest.php
- tests/PhpBrew/VariantBuilderTest.php
- tests/PhpBrew/VariantParserTest.php
In order to be able to build PHP 7.4 using Homebrew-managed dependencies (\#1085), the variant builder should not only be able to build command-line options for the `./configure` command but also generate the `PKG_CONFIG_PATH` environment variable. Currently, it's implemented via storing the `PKG_CONFIG_PATH` components in the build object which then gets passed to the `ConfigureTask`.
This pull request refactors this implementation by introducing the `ConfigureParameters` immutable value object that can be used for building command-line options and environment variables for the `./configure` command without storing anything in the `Build` object state or global state.
All variant closures now take the a value of `ConfigurationParameters` and return a new version augmented with the …
> Refactored building `./configure` command-line options and environment variables

- box.json.dist
The `bz2` variant is part of the `default` variant and is less likely to be missing in the environment.
> Replaced the GZ PHAR compression algorithm with BZ2

- src/PhpBrew/Patches/PHP56WithOpenSSL11Patch.php
- tests/PhpBrew/Patches/PHP56WithOpenSSL11PatchTest.php
- tests/expected/php/5.6.40-php56-openssl11-patch/ext/openssl/openssl.c
- tests/expected/php/5.6.40-php56-openssl11-patch/ext/openssl/xp_ssl.c
- tests/expected/php/5.6.40-php56-openssl11-patch/ext/phar/util.c
- tests/fixtures/php/5.6.40/ext/openssl/openssl.c
- tests/fixtures/php/5.6.40/ext/openssl/xp_ssl.c
- tests/fixtures/php/5.6.40/ext/phar/util.c
The chunks containing mixed line endings were related to the test files which PHPBrew doesn't use, so we can skip them.
```
===> Checking patches...
Checking patch for php5.3.29 multi-sapi
Checking patch for php5.3.x on 64bit machine when intl is enabled.
Checking patch for openssl dso linking patch
Checking patch for php5.6 with openssl 1.1.x patch.
---> Applying patch...
patching file ext/openssl/openssl.c
patching file ext/openssl/xp_ssl.c
patching file ext/phar/util.c
patching file ext/openssl/openssl.c
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 651 with fuzz 1.
```
> Fix the patch corrupted after inlining

- src/PhpBrew/Build.php
- src/PhpBrew/BuildSettings/BuildSettings.php
- src/PhpBrew/VariantBuilder.php
As of [PHP 7.4][1], the oniguruma library is no longer bundled with PHP, instead libonig needs to be available on the system.
[1]: https://www.php.net/manual/en/migration74.other-changes.php#migration74.other-changes.mbstring
> Improved building mbstring on PHP 7.4

- composer.json
- composer.lock
`corneltek/getoptionkit` is kept at `v2.5.0` since c9s/GetOptionKit#54 (`v2.6.0`) introduces the conflict verification that was only fixed in c9s/CLIFramework#105 (`v4.0.0`) which is incompatible with PHP 5.3.
Closes #1103.
> Rebuilt composer.lock from scratch and updated some dependencies

- composer.json
- composer.lock
https://github.com/c9s/GetOptionKit/commit/e6bcd79f09426dcfd4383b659331f26d9cadbf6f (`v2.4.0`) renames `OptionPrinterInterface` to `OptionPrinter` which is incompatible with [c9s/CLIFramework](https://github.com/c9s/CLIFramework/tree/3.0) `3.0.x-dev`.
> Downgraged corneltek/getoptionkit to v2.3.0

- src/PhpBrew/VariantBuilder.php
Use internal `oniguruma` to build mbstring/mbregex in previous PHP version before 7.4.0
> Use internal oniguruma to build mbstring/mbregex in previous PHP version before 7.4.0

- shell/bashrc
- shell/phpbrew.fish
- src/PhpBrew/Command/ConfigCommand.php
- src/PhpBrew/Command/ExtensionCommand/ConfigCommand.php
- src/PhpBrew/Command/InfoCommand.php
- src/PhpBrew/Utils.php
Additionally, cleaned up handling exit codes in shell wrappers and fixed the exit code in `phpbrew ext config`.
Fixes #1134.
> Get the ini info from the currently used PHP instead of the PHPBrew interpreter

- shell/bashrc
In [Zsh](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html), `which phpbrew` resolves to the `phpbrew` alias instead of the binary.
Fixes #1140.
> Use whence -p instead of which in Zsh

- shell/bashrc
- shell/phpbrew.fish
The initialization of `$PHPBREW_ROOT` was accidentally removed in #1098.
> Restored the accidentally removed initialization of $PHPBREW_ROOT in shell wrappers

- src/PhpBrew/VariantBuilder.php
Building PHP with the `mbstring` variant produces the following:
> configure: WARNING: unrecognized options: --with-onig
See https://www.php.net/manual/en/migration74.other-changes.php
> `--with-onig` has been removed.
> Use PKG_CONFIG_PATH instead of --with-onig to configure mbstring

- README.md
Because of the removal of the AppStore, `phpbrew app` no longer exists.
> Remove references to AppStore in README

- shell/phpbrew.fish
> Use the standard shell syntax to redirect stderr for compatibility with Fish 3

- src/PhpBrew/VariantBuilder.php
We should use withPkgConfigPath for icu4c in php7.4.x or compilation will failed.
> Fix intl compilation for php7.4.x in macOS

- src/PhpBrew/Downloader/PhpStreamDownloader.php
Execution continued unnecessarily when there is a download failure, leading to long and confusing traces.
> PhpStreamDownloader: throw exceptions on failure

- src/PhpBrew/PrefixFinder/ExecutablePrefixFinder.php
- src/PhpBrew/VariantBuilder.php
1. Generalize the logic of finding a prefix by executable
2. Add support for building the `pgsql` and `pdo_pgsql` extensions with Homebrew-managed `libpq`.
> Rework the +pgsql variant

- src/PhpBrew/Build.php
- src/PhpBrew/ConfigureParameters.php
- src/PhpBrew/Tasks/ConfigureTask.php
- src/PhpBrew/Utils.php
- src/PhpBrew/VariantBuilder.php
1. Pass `PKG_CONFIG_PATH` via `./configure`. Otherwise, the environment variable is set globally and isn't displayed in debug mode.
2. Add `ConfigureParameters::withOptionOrPkgConfigPath()` since it seems to be a pattern depending on the PHP version.
3. Collect all the needed dependencies for IMAP on macOS from Homebrew.
4. Canonicalize version in the Build constructor. Otherwise, `php-7.3.24RC1` is not less than `7.4`.
> Improve IMAP support on macOS

- completion/zsh/_phpbrew
- src/PhpBrew/Command/UpdateCommand.php
- src/PhpBrew/ReleaseList.php
- src/PhpBrew/Testing/CommandTestCase.php
- tests/PhpBrew/Command/DownloadCommandTest.php
Additionally, all builds older than PHP 7 are moved under the `--old` category.
> Fetch PHP 8 releases from the website

- src/PhpBrew/VariantBuilder.php
- tests/PhpBrew/VariantBuilderTest.php
This PR fixes #1208 by updating ZTS variant for PHP8 builds.
> Update ZTS variant for PHP8 build

- src/PhpBrew/PrefixFinder/ExecutablePrefixFinder.php
- tests/PhpBrew/PrefixFinder/ExecutablePrefixFinderTest.php
This PR replaces a static `pg_config` parameter with the expected `$this->name` in the ExecutablePrefixFinder code.
(Introduced by #1200)
> Fix ExecutablePrefixFinder executable name

- box.json.dist
- composer.json
- composer.lock
- src/PhpBrew/Command/SelfUpdateCommand.php
It is possible that during the upgrade, the new PHPBrew version has the requirements incompatible with the current runtime. It could be a PHP version or required extensions. In such a case, the upgrade will effectively break PHPBrew.
Since we use Box for packaging the binary, we can use its "Check Requirements" feature and validate the downloaded binary before switching to the new version.
If the validation fails, the upgrade will fail as well like follows:
```
$ phpbrew self-update
Updating phpbrew /Users/smorozov/.local/bin/phpbrew...
downloading via curl command
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100    67  100    67    0     0   7444      0 --:--:-- --:--:-- --:--:--  7444
Box Requirements Checker …
```
> Validate the new version during self-update

- src/PhpBrew/Patches/ReadlinePatch.php
- src/PhpBrew/Tasks/BeforeConfigureTask.php
Adds patch to fix build of readline extension on modern Linux distros.
This is a backport of a patch introduced in PHP 7.2:
https://github.com/php/php-src/commit/1ea58b6e78355437b79fb7b1f287ba6688fb1c57
Fixes #889.
> add patch for readline build

- src/PhpBrew/Patches/Apache2ModuleNamePatch.php
- Fix the #1211 and #1221.
- Since the `PHP-8.0` version is released, it seems that the patterns in `configure` and `build/Makefile.global` files are changed. And it should modify pattern in `src/PhpBrew/Patches/Apache2ModuleNamePatch.php` file to let the Apache2 module for `PHP 8.x` can have the version information.
- This PR is the hot patch and it doesn't have the test, but it has the following steps to verify this PR.
- The detailed explanation is available [here](https://github.com/phpbrew/phpbrew/issues/1211#issuecomment-1148534412).
- Prepare the clean and fresh `Ubuntu 20.04` Linux distribution.
- Switch the user to be the `root` user.
- Installing the required packages to run the `PHPBrew`. Please refer [here](https://github.com/phpbrew/phpbrew/wiki/Requirement#ubuntu-2004).
- …
> For issue_#1211

- .github/workflows/build.yml
- .gitignore
- It's related to issue #1216.
- Migrating to the GitHub actions.
- I also organize original works in Travis CI:
- Install the required dependencies and development dependencies via `composer install` command.
- Running the test suites with the PHPUnit.
- After running the PHPUnit successfully, it will download the `coveralls` to upload the code coverage.
- Uploading the phpbrew Phar binary to the Amazon S3.
- After PHPBrew uploading is successful, send the notification to the Gitter.
- And I migrate part of things. They're as follows:
- Setup the from the `PHP 5.3` to `PHP 7.4` versions for running the PHPUnit test suites.
- In the future, it will add the `PHP 8.0` and `PHP 8.1` versions after [related PR](https://github.com/phpbrew/phpbrew/pull/1264) is merged/resolved.
- Just notify …
> Resolves issue #1216

- src/PhpBrew/Extension/Extension.php
1. Run `phpbrew ext install libsodium`
2. `~/.phpbrew/php/php-7.4.27/var/db/libsodium.ini` is created.
Expected content for `~/.phpbrew/php/php-7.4.27/var/db/libsodium.ini`:
```
extension=sodium.so
```
Actual content for `~/.phpbrew/php/php-7.4.27/var/db/libsodium.ini`:
```
extension=libsodium.so
```
> Map `libsodium` extension to `sodium`

- .github/workflows/build.yml
- completion/zsh/_phpbrew
- composer.json
- composer.lock
- src/PhpBrew/Command/InstallCommand.php
- src/PhpBrew/Testing/CommandTestCase.php
- src/PhpBrew/Testing/PatchTestCase.php
- tests/PhpBrew/Command/EnvCommandTest.php
- tests/PhpBrew/ConfigureParametersTest.php
- tests/PhpBrew/Distribution/DistributionUrlPolicyTest.php
- tests/PhpBrew/Downloader/DownloaderTest.php
- tests/PhpBrew/Extension/ExtensionInstallerTest.php
- tests/PhpBrew/Extension/ExtensionManagerTest.php
- tests/PhpBrew/Extension/ExtensionTest.php
- tests/PhpBrew/Extension/Provider/RepositoryDslParserTest.php
- tests/PhpBrew/ReleaseListTest.php
- tests/PhpBrew/Tasks/MakeTaskTest.php
- tests/PhpBrew/VersionDslParserTest.php
- Drop PHP versions that are lower then `PHP 7.2`.
- Fix the Zsh completion when using the higher `corneltek/getoptionkit` version and remove `corneltek/getoptionkit` conflicts.
- The referenced commit is [here](https://github.com/c9s/CLIFramework/commit/39bf80e0e4bc2e33747698503b439e8d28587b72).
- Upgrading the `corneltek/cliframework` to the latest `3.x` patch.
- Upgrading the PHPUnit version.
- Closes #1252.
- Closes #1245.
- Fixing the legacy signature implode syntax.
- The reference is [here](https://www.php.net/manual/en/function.implode.php).
> PHP 8.1 compatibility and fix for PHP7.2 upgrading

- composer.lock
- Upgrading the `composer.lock` file with the `PHP 7.2` version, and the command outputs are as follows:
```sh
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
- Upgrading corneltek/getoptionkit (2.6.1 => 2.7.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
- Downloading corneltek/getoptionkit (2.7.0)
- Upgrading corneltek/getoptionkit (2.6.1 => 2.7.0): Extracting archive
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
27 packages you are using are looking for funding.
Use the …
```
> Upgrade composer.lock with the PHP 7.2 version

- tests/PhpBrew/Command/DownloadCommandTest.php
- tests/PhpBrew/Command/InstallCommandTest.php
- tests/PhpBrew/Command/KnownCommandTest.php
- tests/PhpBrew/Command/UpdateCommandTest.php
- tests/PhpBrew/Extension/ExtensionInstallerTest.php
- tests/PhpBrew/Extension/KnownCommandTest.php
- tests/PhpBrew/VariantBuilderTest.php
- Since migrating to the GitHub actions, some ignored tests in the CI should be migrated, too.
- According to the [default environment variables for the GitHub action](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables), we can use the `GITHUB_ACTIONS` to ignore some tests during GitHub action running.
> Migrate ignored tests Travis CI to GitHub action

- src/PhpBrew/Console.php
- It's related to issue #1301.
Fixing the following deprecated message:
```
PHP Deprecated:  file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 131
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpbrew:0
PHP   2. require() /usr/local/bin/phpbrew:14
PHP   3. PhpBrew\Console->runWithTry($argv = [0 => '/usr/local/bin/phpbrew', 1 => 'ext', 2 => 'install', 3 => 'imagick']) phar:///usr/local/bin/phpbrew/bin/phpbrew:26
PHP   4. file_exists($filename = NULL) phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php:131
Deprecated: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 131
Call Stack: …
```
> Fix file_exists deprecated null arg passing

- src/PhpBrew/Command/ExtensionCommand/KnownCommand.php
- src/PhpBrew/Command/FpmCommand/SetupCommand.php
- src/PhpBrew/Command/InfoCommand.php
- src/PhpBrew/Command/InstallCommand.php
- src/PhpBrew/Command/KnownCommand.php
- src/PhpBrew/Command/ListCommand.php
- src/PhpBrew/Command/ListIniCommand.php
- src/PhpBrew/Command/VariantsCommand.php
- src/PhpBrew/Tasks/ConfigureTask.php
- src/PhpBrew/VariantBuilder.php
- To be consistency, it should replace all `\n` with the `PHP_EOL` to represent the EOL char.
> Replace "\n" with PHP_EOL for consistency

- composer.lock
- Using the `php ~/composer.phar update corneltek/getoptionkit` to upgrade the GetOptionKit dependency.
- Resolving the #1316.
> Upgrade GetOptionKit to the 2.7.2 version

- src/PhpBrew/Command/InstallCommand.php
- It's related to issue #1337.
- The `--with-fpm-systemd` option is added for running configure script command when the current operating system is `Linux`.
- Other operating systems use other background process manager to manage processes.
> Resolve #1337 to check OS when enabling FPM option

- src/PhpBrew/VariantBuilder.php
- tests/PhpBrew/VariantBuilderTest.php
- Adding the `snmp` variant and the reference is available [here](https://www.php.net/manual/en/book.snmp.php).
- The `snmp` extension requires the `net-snmp` package. And it's available in the macOS and Linux-like distributions.
> Add snmp variant support

- src/PhpBrew/VariantBuilder.php
- After checking the Ubuntu distribution, the `Ubuntu 22.04+` can use the `pkg-config` command.
In the `Ubuntu 20.04`, the `libsnmp-dev` package version is `5.8`.
In the `Ubuntu 22.04`, the `libsnmp-dev` package version is `5.9.1`.
> Fix Ubuntu distribution for using pkg-config

- src/PhpBrew/ReleaseList.php
- Resolves #1346.
- Letting `json_decode` be empty array when the decoded result is `null`. And it can also avoid `array_merge` warning.
> Resolves #1346

- src/PhpBrew/Console.php
- It's my fault. I forgot to modify the version const before releasing the `2.2.0` version :(.
> Change 2.1.0 version cont to 2.2.0

- src/PhpBrew/Build.php
- src/PhpBrew/VariantBuilder.php
On macOS on Apple Silicon you get an Allocation of JIT memory failure error at the end of the build of PHP 8.0. This is due to a bug in the bundled PCRE2 library. It's fixed in the bundled version in PHP 8.1, and I think lower versions don't bundle it so you're highly likely to link to a version with the fix.
I wasn't sure how this can be best fixed, and wanted to be able to make it "seamless" and more "intuitive" by detecting Apple Silicon and PHP 8.0 and then forcing it to link to a newer PCRE2 externally, and report if it can't find it, rather than blindly continuing only to fail.
I know there's no other code in phpbrew that appears to check the environment. Happy to discuss a better approach. In an ideal world phpbrew would actually be able to verify the environment before building so …
> fix: Resolve build failure on Apple Silicon of PHP 8.0 due to old bundled pcre2

- src/PhpBrew/Patches/ReadlinePatch.php
This resolves a patch failure (that interestingly gets ignored) when installing PHP > 7.1
There's an OR so effectively match() always returns true - since it will always either be higher or equal to 5.3 or lower or equal to 7.1
> fix: Resolve readline patch attempting to apply to php >7.1 due to OR instead of AND

- src/PhpBrew/VariantBuilder.php
Closes #1278.
Note that this is not a perfect solution as the default variant still defines `json`, but this requires more refactoring as it is used as a public property and the information used is not available when instantiation the `VariantBuilder`.
> fix: Do not add the enable JSON variant for PHP 8.0
