phpbrew/phpbrew

- README.md
You can see on https://github.com/ovr/phpbrew/blob/patch-3/LICENSE
at the bottom of README
> LICENSE must be a link

- shell/bashrc
Breaking change introduced by 08b85ebba6ce7a356ea64bbce0fe66d2a03cb023. Fixes #506.
> zsh which returns the phpbrew function body and not the path

- shell/bashrc
> Revert "Add "-p" to $(command which phpbrew) to ensure a default PATH"

- src/PhpBrew/Extension/ExtensionDownloader.php
- src/PhpBrew/Extension/Provider/GithubProvider.php
> Get correct Github repository tarballs and extracted directory

- src/PhpBrew/Command/KnownCommand.php
> update doc for known command, add --http-proxy and --http-proxy-auth

- README.md
This would have saved me about 45 minutes of source code tracing / trial and error
> Update git install examples

- index.html
Port info form the Readme to GH-Pages, with a little more info since the format seems to be better for a little elaboration here.
> Update GH-Page git install examples

- completion/zsh/_phpbrew
- src/PhpBrew/Command/InstallCommand.php
Small typo fixed on "no-clean" help message
> Typo fixes

- src/PhpBrew/VersionDslParser.php
- tests/PhpBrew/VersionDslParserTest.php
> Fix for phpbrew/phpbrew#599

- composer.json
symfony/yaml is semver compliant.
> Use symfony/yaml ~2.3

- src/PhpBrew/Config.php
- src/PhpBrew/Extension/ExtensionDownloader.php
- src/PhpBrew/ReleaseList.php
Adding proxy to pulls where curl isn't installed
> add proxy settings into file_get_contents

- shell/phpbrew.fish
1. fix issue phpbrew/phpbrew#577
2. add hint for app command
> bugfix and improvements for fish

- src/PhpBrew/Downloader/UrlDownloader.php
Hi there!
I've tried to **phpbrew install x.x.x** and get stuck with CURL error **Failed to connect to www.php.net port 80: Network is unreachable**
**tracepath php.net** shows me that one of the path nodes blocks my request to php.net
After some researching I found a problem: node blocks any requests without valid **userAgent** and it's absolutely impossible to install anything using phpbrew
So, I've fixed it by adding default userAgent to the CURL options array
It's very specific issue and cannot be tested by phpUnit, by it solves my problem and now it works like a charm.
> Network is unreachable php.net fix

- README.ja.md
- README.pt-br.md
Hi, my name is André Teles, I am tried translate it documentation to my language. I want colaborate with your project the way that i can.
> add file README.pt-br.md and translating

- README.ja.md
- README.md
- README.pt-br.md
Hi there, I just noticed that the available options that I have when running `phpbrew variants` are more than the ones listed on the README files, so I created this PR in order to update them all.
Hope it helps :+1:
> Updated README files.

- completion/bash/_phpbrew
- completion/zsh/_phpbrew
- src/PhpBrew/AppStore.php
Updating  behat3 and box2 versions, fixing behat-3 app name.
> App store update

- shell/bashrc
Please read the details [here](https://github.com/phpbrew/phpbrew/issues/862).
> fix #862 dirname bug

- src/PhpBrew/Extension/Provider/Provider.php
- src/PhpBrew/ExtensionList.php
- src/PhpBrew/VariantBuilder.php
Added the `ldap` to be able to compile PHP `--with-ldap`.
> Added the LDAP variant

- src/PhpBrew/Extension/ExtensionManager.php
Currently, the `ext enable` command cannot enable an extension if it was not installed by PHPBrew (only the *.so file exist). This would be useful in the following cases:
1. An extension is built as shared as part of `phpbrew install`. Some extensions like [`opcache`](http://php.net/manual/en/opcache.installation.php#opcache.installation.bundled) and [`gd`](https://github.com/morozov/phpbrew/blob/dc903cccc2dfe45c011b717bd98d1ebab1624e73/src/PhpBrew/VariantBuilder.php#L393) cannot be compiled statically with PHP and thus have to be enabled explicitly after installation.
2. A pre-built extension (e.g. blackfire or newrelic) is downloaded and needs to be enabled by means of PHPBrew.
The first case could be improved even better to the extent that if an extension is built as shared implicitly …
> Improve the "ext enable" command

- composer.lock
Fixes phpbrew/PEARX/issues/5, phpbrew/PEARX/issues/6, phpbrew/PEARX/issues/8 (see [6be60c1...2d361b3](https://github.com/phpbrew/pearx/compare/6be60c1a328ca17ec57c011b51cfbb40d9857ff0...2d361b36e9230390701fd7db46eecd3b13527e25)).
> Updated the locked version of corneltek/pearx

- composer.lock
- tests/PhpBrew/Extension/KnownCommandTest.php
See https://github.com/c9s/CurlKit/pull/3.
> Updated corneltek/curlkit

- .gitignore
- README.cn.md
- README.md
To add chinese readme file.
- Modified some sections of README.md
- Add README.cn.md
- Add `.DS_Store` into .gitignore
- No code was changed.
Users from china will be easier to get started.
Nothing.
Nothing.
> Add README.cn.md

- src/PhpBrew/Command/DownloadCommand.php
- src/PhpBrew/Distribution/DistributionUrlPolicy.php
- src/PhpBrew/Extension/Provider/PeclProvider.php
- src/PhpBrew/ReleaseList.php
- tests/PhpBrew/Distribution/DistributionUrlPolicyTest.php
- tests/PhpBrew/ReleaseListTest.php
- tests/bootstrap.php
- tests/fixtures/php-releases.json
this PR aims to move php.net related site to https. it also suppress #953
> move to https

- src/PhpBrew/Command/InstallCommand.php
Quick typo update while I wait for php to compile.
> Fix typo in sudo warning

- src/PhpBrew/VariantBuilder.php
- tests/PhpBrew/VariantBuilderTest.php
> Use --with-libxml instead of --enable-libxml for PHP 7.4

- src/PhpBrew/VariantBuilder.php
- tests/PhpBrew/VariantBuilderTest.php
> Use --with-zip instead of --enable-zip for PHP 7.4

- src/PhpBrew/Utils.php
> When detecting the library prefix, make sure the whole path exists

- README.ja.md
> Japanese document, add space for markdown head.

- completion/bash/_phpbrew
- completion/zsh/_phpbrew
- src/PhpBrew/AppStore.php
[PhpDocumentor](https://phpdoc.org) allows generating documentation from source files.
Also added missing `psych` to bash completion.
> Added phpdocumentor to `phpbrew app` aka the AppStore

- completion/bash/_phpbrew
- completion/zsh/_phpbrew
- src/PhpBrew/Command/DownloadCommand.php
- src/PhpBrew/Command/InstallCommand.php
- src/PhpBrew/Distribution/DistributionUrlPolicy.php
- tests/PhpBrew/Distribution/DistributionUrlPolicyTest.php
ref: https://externals.io/message/104533
> deprecated mirror option since php.net retired the mirror program

- shell/phpbrew.fish
- src/PhpBrew/Command/AppCommand.php
- src/PhpBrew/Command/AppCommand/GetCommand.php
- src/PhpBrew/Command/AppCommand/ListCommand.php
- src/PhpBrew/Command/ExtensionCommand/ConfigCommand.php
- src/PhpBrew/Command/ExtensionCommand/InstallCommand.php
- src/PhpBrew/Command/ExtensionCommand/ShowCommand.php
- src/PhpBrew/Command/FpmCommand/SetupCommand.php
- src/PhpBrew/Command/FpmCommand/StopCommand.php
- src/PhpBrew/Command/InstallCommand.php
- src/PhpBrew/Downloader/DownloadFactory.php
Major changes:
1. Added completion for all commands, options and arguments.
2. Some descriptions were updated.
3. Argument suggestions are now sourced from the `meta` command, not from ad-hoc shell functions.
4. The `app --list` option has been removed since it duplicates the `app list` command.
> Improved Fish-shell completion

- src/PhpBrew/Patches/PHP53Patch.php
> Removed a trailing comma from the function call in PHP53Patch.php

- src/PhpBrew/CommandBuilder.php
- src/PhpBrew/Extension/ExtensionInstaller.php
- src/PhpBrew/Tasks/ConfigureTask.php
- tests/PhpBrew/CommandBuilderTest.php
> Improved escaping of command line arguments

- .travis.yml
- phpunit.xml.dist
Additionally, disabled verbosity in PHPUnit.
> Disable travis builds on other branches than master

- .gitignore
- src/PhpBrew/Testing/VCRAdapter.php
1. Added the recordings to .gitignore.
2. Fixed argument order in the call to implode().
> Fixed VCR issues

- completion/bash/_phpbrew
- completion/zsh/_phpbrew
- shell/phpbrew.fish
- src/PhpBrew/Command/DownloadCommand.php
- src/PhpBrew/Command/InstallCommand.php
> Removed the unsupported mirror option from the download and install subcommands

- composer.json
- composer.lock
- src/PhpBrew/Extension/Provider/PeclProvider.php
Explicitly declared dependency on SimpleXML extension.
> Removed package dependency on the DOMDocument extension

- .travis.yml
- composer.json
- composer.lock
Cannot bump the version constraint to 8.5 because some tests are inherited from the ones in the CLIFramework package which cannot be updated.
> Updated the locked PHPUnit version to 7.5

- completion/zsh/_phpbrew
- src/PhpBrew/Command/RemoveCommand.php
The command completion has been broken by #1100.
> Fixed shell completion of the remove command

- index.html
Removes reference to `phpbrew app` from gh-pages
> Remove references to phpbrew app from gh-pages

- README.ja.md
Hi, all. 
`README.ja.md`(for Japanese) is out of date, so I've updated the document to follow the latest version of `README.md`.
> Updates README.ja.md to catch up with the latest

- shell/bashrc
This is a basic fix.
Note: I did not find the related code for other shell prompt (they may even not have a similar option)
if it exists it could be done in a separate PR
> Fix phpbrew bash prompt for php 8

- completion/bash/_phpbrew
- completion/zsh/_phpbrew
- shell/bashrc
- shell/phpbrew.fish
- src/PhpBrew/Command/ConfigCommand.php
- src/PhpBrew/Command/ExtensionCommand/ConfigCommand.php
- src/PhpBrew/Command/ExtensionCommand/DisableCommand.php
- src/PhpBrew/Command/ExtensionCommand/EnableCommand.php
- src/PhpBrew/Command/InstallCommand.php
- src/PhpBrew/Config.php
- src/PhpBrew/ConfigureParameters.php
- src/PhpBrew/Extension/Extension.php
- src/PhpBrew/Extension/ExtensionManager.php
Build php with different php.ini for each SAPI: apache2, fpm, cli. Extensions draw their config from the different directories too.
Fixes #820 #1165
> PHP will be built using different configs for different SAPIs

- README.md
> Resolves issue #1271

- CONTRIBUTING.md
- Updating contributing guide to add the releasing version tips.
> Update contributing about releasing version tips

- .github/workflows/tests.yaml
- composer.json
- composer.lock
- [Resolves](https://github.com/phpbrew/phpbrew/commit/ff0735da06371f0cdf5414143ccf66b6ebb0f17c) https://github.com/phpbrew/phpbrew/issues/1331
- Resolves #1300.
- Upgrading the `corneltek/cliframework` to resolve dynamic properties issue. And the related commit is available [here](https://github.com/c9s/CLIFramework/commit/0e69e4d9d8ee6c8b5abb7ebf0cf846e47d93b656).
- Running the `composer update corneltek/cliframework` command and outputs are as follows:
```sh
$ composer update corneltek/cliframework
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
- Upgrading corneltek/cliframework (3.0.x-dev 01cee2d => 3.0.x-dev 0e69e4d)
Writing lock file
Installing dependencies from lock file (including require-dev) …
```
> Resolves #1331

- .github/workflows/release.yaml
- Resolves #1355.
- Correct the `phpbrew.asc` file name.
- Correct the specific zipped artifact file paths.
> Resolves issue #1355
